### ISSUE TITLE
Classes should follow PSR-4

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/search#11]
Classes in src/ folder do not follow [PSR-4](https://www.php-fig.org/psr/psr-4/) for namespace and filenames. It causes issues with auto wiring.

E.g. src/Entity/AutoCompleteResult.php should be class AutoCompleteResult in namespace Mathematicator\Search\Entity (instead of current: Mathematicator\Search).

**Comment by janbarasek** [comment]
Nette also does not use the PSR-4 for autoloading classes.

I think this is a big BC break that has to be done carefully, due to the compatibility of other packages.

**Comment by flokixdev** [comment]
So, I am not able to autowire services in Symfony.

Any thoughts, how to solve this?
![image](https://user-images.githubusercontent.com/2387790/81206548-8d99f900-8fcc-11ea-9658-2d18dce045ef.png)

My services.yaml is:
```yaml
# ... other config ...
    Mathematicator\Search\:
        resource: '../vendor/mathematicator-core/search/src/*'
        exclude: '../vendor/mathematicator-core/search/src/{Entity}'
```
